### ISSUE TITLE
Issues with the Powershell configuration.

### ISSUE THREAD

**Issue by stehouri83** [microsoft/AzStackHCISandbox#5]
Once the Vm has been deployed into Azure and I have logged in using public IP.

The next stage is using the New-AzSCH Powershell script on the descktop of the server.

I have followed the instructions and run with PowerShell. I left the deployment to run.

After I returned after a few hours as directed the Powershell session window is gone but I have no Windows Admin Center icon on the descktop.

I have redeployed twice and have had this issue twice.

**Comment by stdistef** [comment]
> Once the Vm has been deployed into Azure and I have logged in using public IP.
> 
> The next stage is using the New-AzSCH Powershell script on the descktop of the server.
> 
> I have followed the instructions and run with PowerShell. I left the deployment to run.
> 
> After I returned after a few hours as directed the Powershell session window is gone but I have no Windows Admin Center icon on the descktop.
> 
> I have redeployed twice and have had this issue twice.

I have the same issue.     I ran the powershell from a Powershell window instead of launching the built in script to see where she aborts.    I found it here:  
VERBOSE: Exporting function 'Disable-NetAdapterPacketDirect'.
VERBOSE: Enabling PSRemoting on AZSMGMT
**No MSFT_ScheduledTask objects found with property 'TaskName' equal to 'ServerManager'.  Verify 
the value of the property and retry.**
At C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1:1046 char:5
+     Invoke-Command -ComputerName azsmgmt -Credential $localCred  -Scr ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ServerManager:String) [Get-ScheduledTask], CimJob 
   Exception
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_TaskName,Get-ScheduledTask
    + PSComputerName        : azsmgmt
 

PS C:\AzHCI_Sandbox\AzSHCISandbox-main> 
![image](https://user-images.githubusercontent.com/35927980/149632938-6e82d45a-d01d-4805-98ec-20ac3cdedfa4.png)

**Comment by mgodfre3** [comment]
I will begin looking at this. Thanks for the heads up.

**Comment by mgodfre3** [comment]
Issue should be resolved now, had to update link for vhd downloads to use a gui based server os. It previously was using core. Please redeploy and confirm.

**Comment by NakayamaKento** [comment]
I have found the new issue.

![image](https://user-images.githubusercontent.com/40586116/150350289-f00d723f-74f0-4d4b-bb0c-d8e635643004.png)


Package 'Az.Resources' failed to be installed because: There is not enough space on the disk.
At C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1:2028 char:5
+     Invoke-Command -VMName AzSMGMT -Credential $localCred -ScriptBloc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (Az.Resources:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
    + PSComputerName        : AzSMGMTI have

**Comment by mgodfre3** [comment]
Deployed new GUI VHD in the Storage Account, this will resolve the issue and only requires a redeployment for anyone who has not successfully deployed as of yet.
